name: clostel
description: A cross-platform music player for the way you listen.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  discord_rich_presence: ^1.1.1
  file_picker: ^10.2.0
  flutter_liquid_glass_kit: ^1.5.0
  http: ^1.3.0
  just_audio: ^0.10.4
  just_audio_media_kit: ^2.1.0
  media_kit_libs_linux: any
  media_kit_libs_windows_audio: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
  fonts:
    - family: FunnelDisplay
      fonts:
        - asset: assets/fonts/FunnelDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/FunnelDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FunnelDisplay-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
