name: clostel
description: A cross-platform music player for the way you listen.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_liquid_glass_kit: ^1.5.0
  just_audio: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
